[package]
name = "study_buddy_cli"
version = "0.1.0"
edition = "2021"
chrono = "0.4"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.31"
lazy_static = "1.4.0"
postgres = "0.19.7"
